models/Books.js
Added the Book schema to define the structure of book documents in MongoDB. This schema includes fields for title, author, ISBN, genre, available copies, and a Base64-encoded image. Timestamps are also enabled to track when books are created or updated.
=> Added Book schema to define structure of book documents in MongoDB

public/index.html, public/js/Add-Book.js, utils/Add-BookUtils.js
Need to revert as some minor changes are needed to be made in add-book branch code.
=> Revert "Reverted to an old commit and resolved merge conflict and made new changes."

.vscode/settings.json, index.js, public/css/style.css, public/index.html, public/js/getBook.js, public/js/updateBook.js, utils/updateBookUtil.js
Feature to update book details and preview the image with validation and error-handling has been made
=> Update feature Implemented

public/css/style.css, public/index.html
Improved the style for the update form fields by making all of the fields the same length
=> Improved the style for the update form fields

index.js, models/BorrowTransaction.js, public/css/style.css, public/index.html, public/js/Add_Transaction.js, utils/Add-BookUtils.js
This pull request introduces the ability for users to borrow and return books within the BookTrack application. The feature allows for seamless tracking of book transactions, enhancing the overall user experience in managing library resources.
=> Addbook transaction feature

public/js/getBook.js, utils/getBookUtils.js
Successfully implemented error handling and input validation for edge cases in Search and Get books such as
Empty search string
Special characters in my search string
Invalid parameter
Long queries
No data found
=> Implemented error handling and input validation for edge cases

index.js, public/js/Add_Transaction.js, public/js/updateBook.js, utils/updateBookUtil.js
Reverts guyidk/BookTrack_DevOps_Project#45
=> Revert "Implemented GET by ID for books with comprehensive error handling"

public/index.html, public/js/Add_Transaction.js
This PR introduces comprehensive input validation for the book_id, borrowDate, returnDate, and borrower_name fields in the addTransaction function to ensure data integrity and provide meaningful feedback to users. These validations enhance the user experience by catching input errors before submission and preventing unnecessary backend requests.
=> Handling validation for book_id  return_date and  borrowDate and  name 

public/css/style.css, public/index.html, public/js/getBook.js
Rectified The Position of my Search button
=> Improving the Design of The Search button

public/css/style.css, public/index.html, public/js/Add-Book.js, utils/Add-BookUtils.js
Reverts guyidk/BookTrack_DevOps_Project#57
=> Revert "Implement Add Book Feature with Validation and Confirmation"

public/js/updateBook.js
Added a confirmation message to allow users to review their changes one last time before updating
=> Added confirmation message before updating

public/index.html, public/js/updateBook.js
Added comments for better understanding of my code to other collaborators
=> Added comments for better understanding

public/js/getBook.js
To ensure clarity and maintainability, with comprehensive comments added throughout.
=> Added Comments to My getBook.js File

index.js
Fixed the error after forgetting to change the file name in index.js
=> Fixed an error caused by renamimng files

.vscode/settings.json
=> Deleted settings.json

utils/add-transaction-util.js
- if book_id exist then it will show an mesage that user already borrow the book
=> handle book_id when exist

public/js/update-book.js, utils/update-book-util.js
Added validation to ensure the title is unique when updating. If the title already exists in the database, the user will receive an error message. The user will still be able to click Update without encountering issues if the title remains unchanged
=> Add validation to ensure title is unique on update

index.js, public/js/update-book.js, utils/update-book-util.js
Added character limits: 100 characters for title and 150 characters for author
=> Added character limits to title(100) and author(150)

public/js/update-book.js, utils/update-book-util.js
As MongoDB has a size limit of 16mB I added validation to prevent admins form uploading a image with a file size more than 16MB
=> Added 16MB size limit to image

public/js/add-book.js
Added maximum character limit for Title(100 characters).
Added maximum character limit for Author's name(150 characters).
Added maximum file size for image size(16MB).
=> Added validations for Image size and (Title and author) character limits

utils/search-book-util.js
=> Removed irrelevant Comment

utils/update-book-util.js
Added backend validation for available copies such that the copies cannot be less than 1
=> Added backend validation for available copies

public/css/style.css, public/index.html, public/js/update-book.js
Added separate overlay for update form instead of reusing add form's overlay
=> Added separate overlay for update form instead of reusing add form's overlay
